### ISSUE TITLE
Embedding images fails

### ISSUE THREAD

**Issue by dinamic** [asahasrabuddhe/laravel-mjml#28]
Often times with email messages we want to embed the images. Seems it is not possible with this package.

The usual syntax is along the lines of:

```
<img src="{{ $message->embed(public_path('img/some-random-image.png')) }}" />
```

This fails with an exception tho:

```
Undefined variable: message 
```

Stack trace:

```
#0 /home/XX/resources/views/emails/users/XX.blade.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/home/XX/s...', 36, Array)
#1 /home/XX/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/XX/s...')
#2 /home/XX/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/XX/s...', Array)
#3 /home/XX/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('/home/XX/r...', Array)
#4 /home/XX/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/home/XX/r...', Array)
#5 /home/XX/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#6 /home/XX/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /home/XX/vendor/asahasrabuddhe/laravel-mjml/src/Process/MJML.php(64): Illuminate\\View\\View->render()
#8 /home/XX/vendor/asahasrabuddhe/laravel-mjml/src/Mail/Mailable.php(66): Asahasrabuddhe\\LaravelMJML\\Process\\MJML->renderHTML()
#9 /home/XX/vendor/asahasrabuddhe/laravel-mjml/src/Mail/Mailable.php(41): Asahasrabuddhe\\LaravelMJML\\Mail\\Mailable->buildMjmlView()
#10 /home/XX/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(153): Asahasrabuddhe\\LaravelMJML\\Mail\\Mailable->buildView()
```

**Comment by dinamic** [comment]
I suspect the reason for lacking this feature is because the original Laravel implementation calls `render()` not on the View, but on the mailer instance.

**Comment by dinamic** [comment]
I presume the inspiration behind implementing MJML support was the markdown one, which lacks support for `$message` as well.

https://github.com/laravel/framework/issues/19046

**Comment by asahasrabuddhe** [comment]
@dinamic you’re right but I’m open to implementing it in a different way to make it possible

**Comment by shayneoneill** [comment]
Was this ever resolved?

**Comment by javiercno** [comment]
I'm also interested in this
